"- options
"-------------------------------------------------------------------------------
"- colorscheme
colorscheme default

"- background
set background=dark

"- Syntax highlighting
syntax on

"- Relative and absolute line numbers combined
set number

"- Colored Column
set colorcolumn=80

"- Scroff
set scrolloff=5

"- search as you type
set incsearch 

"- Text wrapping
set nowrap

"- Save undo history
set undofile 
